name: publish-deno

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check publish
        run: deno publish --dry-run
      - name: Publish to JSR
        run: timeout 10m deno publish
